In [12]:
import numpy as np

In [81]:
%run environment.py
%run actionValueFunction.py

In [ ]:
Q = ActionValueFunction(input_size=num_rows*num_cols + 1, output_size=num_cols)

In [82]:
num_rows = 4
num_cols = 5
num_wins = 3
env = Environment(num_rows, num_cols, num_wins)

In [88]:
env.reset()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [93]:
_, reward, done = env.step(action = 2, player=1, Q=Q)
print(reward, done)
env.render()

1 True
|   |   |   |   |
|   |   |   |   |
|   | O | X |   |
| O | X | X |   |
| X | X | O | O |
-----------------


1 True


In [59]:
env.board

array([ 1.,  0., -1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  0.,  0., -1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.])

In [47]:
state_action = np.concatenate((board, [1])).reshape(1, -1)
print(state_action)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
